project_name: giftbox
release:
  github:
    owner: matthewmueller
    name: giftbox
builds:
- goos:
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  main: ./giftbox
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: giftbox
- goos:
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
fpm:
  vendor: giftbox
  maintainer: Matthew Mueller <mattmuelle@mgail.com>
  description: Giftbox release
  formats:
    - rpm
  # We need ps (procps) & su (util-linux) and initscripts for init.d
  # Note: only needed inside the amazonlinux docker container
  dependencies:
    - procps
    - util-linux
    - initscripts
  files:
    ./vendor/monit/bin/monit: /usr/local/bin/monit
    ./vendor/monit/man/man1/monit.1: /usr/share/man/man1/monit.1
    ./monit/monitrc: /usr/local/etc/monitrc
    ./monit/init.sh: /etc/init.d/monit
    ./monit/monit.d/: /usr/local/etc/monit.d


# archive:
#   format: tar.gz
#   name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
#     .Arm }}{{ end }}'
#   files:
#   - licence*
#   - LICENCE*
#   - license*
#   - LICENSE*
#   - readme*
#   - README*
#   - changelog*
#   - CHANGELOG*
# snapshot:
#   name_template: SNAPSHOT-{{ .Commit }}
